
web:
  container_name: nodeJS
  
  build: .

  ports:
    - "3000:3000"

  volumes:
    - ./node_modules:/npm

  command: bash -c "npm install; nodemon server.js --color=always"

  links: 
    - mongo

mongo:
  image: mongo
  
  container_name: mongo

  volumes:
    - ./data:/db

  ports:
      - "27017:27017"
      