web:
  container_name: nodeJS
  
  build: .

  ports:
    - "3000:3000"

  volumes:
    - ./node_modules:/npm

  command: bash -c "npm install; nodemon server.js --color=always"

  links: 
    - mysql

mysql:
  image: mysql:5.6
  
  container_name: MySQLDB

  environment:
    - MYSQL_USER=wrj
    - MYSQL_PASSWORD=wrj
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE:=default

  volumes:
    - ./data:/mysql

  ports:
      - "3306:3306"
      