service:
  image: node:9.8

  container_name: nodeJS

  volumes: 
      - .:/app

  ports:
    - "3000:3000"

  command: bash -c "npm install; nodemon app.js --color=always"

  links: 
    - mongo

mongo:
  image: mongo:latest

  container_name: mongoNode

  ports:
    - "27017:27017"
    