
app:
  container_name: nodeJS

  restart: always

  build: .

  ports:
    - "8080:8080"

  command: bash -c "npm install; nodemon server.js --color=always"

  links: 
    - mongo

mongo:
  image: mongo
  
  container_name: mongo

  volumes:
    - ./data:/db

  ports:
      - "27017:27017"
      